apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: rux
servers: 1
agents: 3
image: rancher/k3s:v1.28.12-k3s1
ports:
  - port: 8080:30080
    nodeFilters:
      - agent:*
  - port: 9090:30090
    nodeFilters:
      - agent:*
options:
  k3d:
    disableLoadbalancer: false
    disableImageVolume: false
    disableRollback: false
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
