apiVersion: v1
kind: Service
metadata:
  name: {{ include "rux.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rux.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "rux.selectorLabels" . | nindent 4 }}
  ports:
    - name: s3
      port: {{ .Values.service.s3Port }}
      targetPort: 8080
      {{- if .Values.service.s3NodePort }}
      nodePort: {{ .Values.service.s3NodePort }}
      {{- end }}
      protocol: TCP
